#! /usr/bin/python
import random
x = random.randint(1,9)
y = random.randint(1,9)

# Вводим первое число
#x = int(input("Введите число X: "))
# Вводим второе число
#y = int(input("Введите число Y: "))

# Вычисляем значение
a = x + y
b = x - y
c = x * y
d = x / y
e = x // y
f = x ** y

# Выводим результат на экран
print("X =",x, "Y =",y)
if x < y:
    print('X меньше Y')
elif x == y:
    print('X равен Y')
else:
    print('X больше Y')
print("X+Y =",a,"\nX-Y =",b,"\nX*Y =",c,"\nX/Y =",d,"\nX//Y =",e,"\nX**Y =",f)

# Сравниваем полученый результат
l_num = (a, b, c, d, e, f)
max_num = max(l_num)
print("Наибольшее число:", max_num)



