#! /usr/bin/python
import random
# Генерация случайного чисела для X и Y от 1 до 9
x = random.randint(1,9)
y = random.randint(1,9)

# Вводим первое число
#x = int(input("Введите число X: "))
# Вводим второе число
#y = int(input("Введите число Y: "))

# Вычисляем значение
a = x + y
b = x - y
c = x * y
d = x / y
e = x // y
f = x ** y

# Выводим на экран значение X и Y
print("X =",x,"Y =",y)

# Сравниваем X и Y между собой, результат выводим на экран
if x < y:
    print('X меньше Y')
elif x == y:
    print('X равен Y')
else:
    print('X больше Y')

# Выводим результат примеров на экран
print("X+Y =",a,"  X-Y =",b,"  X*Y =",c,"  X/Y =",d,"  X//Y =",e,"  X**Y =",f)

# Сравниваем полученый результат через MAX
l_num1 = (a, b, c, d, e, f)
max_num = max(l_num1)
print("Наибольшее число через MAX:", max_num)

# Сравниваем полученый результат через FOR
def large(arr):
    max_ = arr[0]
    for ele in arr:
        if ele > max_:
           max_ = ele
    return max_

l_num2 = (a, b, c, d, e, f)
result = large(l_num2)
print("Наибольшее число через FOR:", result)

