#! /usr/bin/python

# Вводим первое число
x = int(input("Введите число X: "))
# Вводим второе число
y = int(input("Введите число Y: "))
# Вычисляем
print("X+Y=",x + y)
print("X-Y=",x - y)
print("X*Y=",x * y)
print("X/Y=",x / y)
print("X//Y=",x // y)
print("X**Y=",x ** y)


# Сравниваем полученый результат
