#! /usr/bin/python

# Вводим первое число
#x = int(input("Введите число X: "))
x = 4
# Вводим второе число
#y = int(input("Введите число Y: "))
y = 4
# Вычисляем значение
a = x + y
b = x - y
c = x * y
d = x / y
e = x // y
f = x ** y

# Выводим результат на экран
print("X =",x, "Y =",y)
if x < y:
    print('X меньше Y')
elif x == y:
    print('X равен Y')
else:
    print('X больше Y')
print("X+Y =",a,"\nX-Y =",b,"\nX*Y =",c,"\nX/Y =",d,"\nX//Y =",e,"\nX**Y =",f)

# Сравниваем полученый результат

